- name: Install and configure Grafana
  hosts: web
  become: yes
  tasks:
    - name: Install Grafana from Ubuntu repository
      apt:
        name: grafana
        state: present

    - name: Start and enable Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Wait for Grafana to start
      wait_for:
        port: 3000
        delay: 10
        timeout: 30
