- name: Install Grafana manually
  hosts: web
  become: yes
  tasks:
    - name: Download Grafana
      get_url:
        url: https://dl.grafana.com/oss/release/grafana_10.2.3_amd64.deb
        dest: /tmp/grafana.deb

    - name: Install dependencies for Grafana
      apt:
        name:
          - adduser
          - libfontconfig1
        state: present

    - name: Install Grafana
      apt:
        deb: /tmp/grafana.deb

    - name: Start and enable Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Wait for Grafana to start
      wait_for:
        port: 3000
        delay: 10
        timeout: 60
