- name: Setup Node.js metrics with prom-client
  hosts: web
  become: yes
  tasks:
    - name: Install prom-client in backend
      npm:
        name: prom-client
        path: /home/ubuntu/travelmemory/backend
        state: present

    - name: Create metrics endpoint in backend
      lineinfile:
        path: /home/ubuntu/travelmemory/backend/index.js
        insertafter: 'const app = express()'
        line: |
          const client = require('prom-client');
          const collectDefaultMetrics = client.collectDefaultMetrics;
          collectDefaultMetrics({ timeout: 5000 });

          const httpRequestDurationMicroseconds = new client.Histogram({
            name: 'http_request_duration_ms',
            help: 'Duration of HTTP requests in ms',
            labelNames: ['method', 'route', 'code'],
            buckets: [0.1, 5, 15, 50, 100, 200, 300, 400, 500]
          });

          app.use((req, res, next) => {
            res.locals.startEpoch = Date.now();
            next();
          });

          app.get('/metrics', async (req, res) => {
            res.set('Content-Type', client.register.contentType);
            res.end(await client.register.metrics());
          });
