- name: Install and configure Prometheus
  hosts: web
  become: yes
  tasks:
    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.47.2/prometheus-2.47.2.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create Prometheus directory
      file:
        path: /opt/prometheus
        state: directory

    - name: Copy Prometheus config
      copy:
        src: prometheus.yml
        dest: /opt/prometheus/prometheus.yml

    - name: Create Prometheus service
      copy:
        content: |
          [Unit]
          Description=Prometheus
          After=network.target

          [Service]
          User=ubuntu
          Group=ubuntu
          Type=simple
          ExecStart=/opt/prometheus-2.47.2.linux-amd64/prometheus --config.file=/opt/prometheus/prometheus.yml --web.listen-address=:9090
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/prometheus.service

    - name: Reload systemd and start Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes
        daemon_reload: yes
