- name: Configure MongoDB Server
  hosts: db
  become: yes
  tasks:
    - name: Import MongoDB public key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-6.0.asc
        state: present

    - name: Add MongoDB repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse
        state: present
        filename: mongodb

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present

    - name: Start and enable MongoDB
      service:
        name: mongod
        state: started
        enabled: yes

    - name: Allow remote access in MongoDB config
      lineinfile:
        path: /etc/mongod.conf
        regexp: '^  bindIp:'
        line: '  bindIp: 0.0.0.0'
        backup: yes
      notify: Restart MongoDB

    - name: Create admin user (first time setup)
      shell: |
        mongosh --eval "
          db = db.getSiblingDB('admin');
          if (db.getUser('admin') == null) {
            db.createUser({
              user: 'admin',
              pwd: 'adminpassword',
              roles: ['root']
            });
          }
        "
      args:
        warn: false
      register: mongo_result
      changed_when: "'success' in mongo_result.stdout"

    - name: Create application database user
      community.mongodb.mongodb_user:
        login_user: admin
        login_password: adminpassword
        database: admin
        name: traveluser
        password: travelpass
        roles: 
          - role: readWrite
            db: travelmemory
          - role: dbAdmin
            db: travelmemory
        state: present

  handlers:
    - name: Restart MongoDB
      service:
        name: mongod
        state: restarted